name: deploy-to-heroku

on:
  push:
    branches: [ master ]

jobs:
      
  deploy:
    name: Deploy to Heroku
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
     
      