name: deploy-to-heroku

on:
  push:
    branches: [ master ]
    
env:
  HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
  APP_NAME: ${{secrets.APP_NAME }}
  ACCOUNT_EMAIL: ${{secrets.ACCOUNT_EMAIL}} 

jobs:
      
  deploy:
    name: Deploy to Heroku
    runs-on: ubuntu-latest
    steps:

    # Clone the repository
    - name: Checkout
      uses: actions/checkout@v2

    # Build Docker image
   - name: "Deploy the web dyno"
        uses: "akhileshns/heroku-deploy@v3.12.12"
        with:
          docker_heroku_process_type: web
          heroku_api_key: $HEROKU_API_KEY
          heroku_app_name: $APP_NAME
          heroku_email: $ACCOUNT_EMAIL
          justlogin: true

    - name: "Login to heroku registry"
      run: heroku container:login

    - name: "Build and push to heroku registry"
      run: heroku container:push web --app $APP_NAME

    - name: "Releases the container"
      run: heroku container:release web --app $APP_NAME